// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsW6sjNUAjBAjLX_UF451lA4KxvZm_1FY',
    appId: '1:279563996410:web:5f3ac925e79c733363cd43',
    messagingSenderId: '279563996410',
    projectId: 'ecommerceapp-2e812',
    authDomain: 'ecommerceapp-2e812.firebaseapp.com',
    storageBucket: 'ecommerceapp-2e812.firebasestorage.app',
    measurementId: 'G-L37L7KKVLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Tty8ouL5Rr8lydwcl6GW_QYsqNm_F6s',
    appId: '1:279563996410:android:da1c5785c503d52263cd43',
    messagingSenderId: '279563996410',
    projectId: 'ecommerceapp-2e812',
    storageBucket: 'ecommerceapp-2e812.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDazvnPUEHlFcQ7I5JDZnGdettivFtVe-o',
    appId: '1:279563996410:ios:36f0772121d0d5be63cd43',
    messagingSenderId: '279563996410',
    projectId: 'ecommerceapp-2e812',
    storageBucket: 'ecommerceapp-2e812.firebasestorage.app',
    androidClientId: '279563996410-2ga2sru7n27nhte8dcced8bh5llko23e.apps.googleusercontent.com',
    iosClientId: '279563996410-1uu0bg7pisbrmgi5bjua7grjtp0f2f4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.ytEcommerceAdminPanel',
  );
}
